### ISSUE TITLE
Congratulations and thanks!!!!!

### ISSUE THREAD

**Issue by igarca** [taylor-hartman/Flashbang#6]
The app is amazing and extremely useful but simple at the same time. It's great to study, thank you very much and congratulations. It is very complete.
Just that, I needed to let you know and thank you.
You can delete the issue:-))

**Comment by taylor-hartman** [comment]
lol thank you, im glad to hear you have enjoyed it

**Comment by igarca** [comment]
yes, because it's quite useful for studying.
Just one suggestion: could you make something similar to Excel sheets? To have one sheet for each particular subject, with its corresponding bunches.
Thank you!

**Comment by taylor-hartman** [comment]
So something like tabs or folders on the home page for organizational purposes?

**Comment by igarca** [comment]
Exactly, folders or tabs, for organizational purposes.
Thank you!!!

**Comment by taylor-hartman** [comment]
over the past two weeks I started trying to implement it. The resulting commits are on the "megabunch" branch (called that because I also was trying to implement the ability to study multiple bunches at once, hence megabunch). However I have run into a decent amount of challenges while trying to do so. At this point I think I have and idea of how to make it work, but im not certain. Adding both the folders and mega bunch functions are definitely the largest priority steps i wanna take next for development; i just want to make sure that it is possible while maintaining a clean UI and functionality, so it might take a bit.

**Comment by taylor-hartman** [comment]
sorry for the long delay, flashbang v1.3.0 experimental is now released and has folders implemented. it can be found at: [https://flashbang.lol/experimental.html](https://flashbang.lol/experimental.html )

**Comment by igarca** [comment]
Thank you!!! Once I try it out I'll let you know if I find any bugs. Thanks for your work and have a good summer!
PS: Would be awesome a portable version! :)
